Ανοίγω το αρχείο κάνω mapping και ταυτόχρονα γεμίζω τα διανύσματα που θα χρησιμοποιήσω για να φτιάξω τον sparse πίνακα

In [38]:
ratingsFile = open('pruned_data.csv',encoding = 'utf8',errors='ignore')
users = {}
business = {}
user_counter = 0
business_counter = 0
row = []
col = []
data = []
for line in ratingsFile:
    lineValues = line.split(',')
    user_id = lineValues[0]
    business_id = lineValues[1]
    rating = float(lineValues[2])
    data.append(rating)
    if user_id not in users:
        row.append(user_counter)
        users[user_id] = user_counter
        user_counter += 1
    else:
        row_number = users[user_id]
        row.append(row_number)
    if business_id not in business:
        col.append(business_counter)
        business[business_id] = business_counter
        business_counter += 1
    else:
        col_number = business[business_id]
        col.append(col_number)
ratingsFile.close()

Δημιουργώ τον sparse πίνακα με βάση τα row col και data διανύσματα που έβγαλα από το αρχείο

In [39]:
import scipy.sparse as sp_sparse
import numpy as np
row = np.array(row)
col = np.array(col)
print(col)
print(row)
data = np.array(data)
M = sp_sparse.csr_matrix((data,(row,col)),shape=(len(users),len(business)))
print(M)
print(M.toarray())

[   0    1    2 ...  767 1189 3023]
[   0    0    0 ... 4793 4793 4793]
  (0, 0)	4.0
  (0, 1)	4.0
  (0, 2)	5.0
  (0, 3)	4.0
  (0, 4)	4.0
  (0, 5)	5.0
  (0, 6)	4.0
  (0, 7)	4.0
  (0, 8)	2.0
  (0, 9)	5.0
  (0, 10)	5.0
  (0, 11)	4.0
  (0, 12)	5.0
  (0, 13)	4.0
  (0, 14)	4.0
  (0, 15)	4.0
  (0, 16)	2.0
  (0, 17)	3.0
  (0, 18)	4.0
  (0, 19)	4.0
  (0, 20)	5.0
  (0, 21)	3.0
  (0, 22)	4.0
  (0, 23)	4.0
  (0, 24)	4.0
  :	:
  (4792, 2322)	4.0
  (4792, 2423)	5.0
  (4792, 2741)	4.0
  (4792, 2845)	2.0
  (4792, 2982)	5.0
  (4792, 3138)	3.0
  (4793, 40)	5.0
  (4793, 63)	5.0
  (4793, 414)	3.0
  (4793, 767)	5.0
  (4793, 814)	4.0
  (4793, 916)	3.0
  (4793, 972)	4.0
  (4793, 1076)	5.0
  (4793, 1189)	1.0
  (4793, 1634)	3.0
  (4793, 1928)	2.0
  (4793, 2218)	5.0
  (4793, 2388)	4.0
  (4793, 2593)	5.0
  (4793, 2995)	3.0
  (4793, 3023)	5.0
  (4793, 3068)	5.0
  (4793, 3429)	5.0
  (4793, 3893)	3.0
[[4. 4. 5. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. 

Διαλέγω τυχαία 5% του συνόλου των μη μηδενικών μετρήσεων και αφαιρώ μη μηδενικά κελιά του πίνακα μηδενίζοντας τα

In [40]:
from scipy.sparse import csr_matrix
import random
non_zero_cells = csr_matrix.nonzero(M)
removed_cells = []
num_non_zero = len(non_zero_cells[0])
cells_to_remove = int(0.05*len(non_zero_cells[0]))
while cells_to_remove > 0:
    k = random.randint(0,num_non_zero)
    i = non_zero_cells[0][k]
    j = non_zero_cells[1][k]
    if (i,j) not in removed_cells:
        M[i,j] = 0
        removed_cells.append((non_zero_cells[0][i],non_zero_cells[1][i]))
        cells_to_remove -= 1
print(cells_to_remove)
print(non_zero_cells)
print(removed_cells)

), (21, 1586), (13, 1092), (7, 699), (37, 2090), (16, 1246), (7, 817), (28, 243), (6, 127), (5, 547), (3, 295), (14, 1101), (15, 1206), (9, 975), (6, 763), (7, 809), (5, 448), (36, 1961), (13, 375), (0, 46), (11, 91), (2, 182), (14, 1147), (5, 421), (3, 286), (14, 847), (7, 562), (39, 2490), (31, 1076), (18, 216), (18, 1273), (28, 348), (10, 988), (2, 193), (9, 968), (8, 899), (10, 63), (33, 1979), (26, 1699), (37, 49), (15, 1209), (39, 1289), (39, 709), (6, 683), (20, 1483), (7, 656), (6, 729), (5, 318), (29, 1885), (8, 864), (26, 1712), (2, 85), (41, 1468), (37, 228), (37, 2361), (6, 757), (37, 246), (40, 509), (28, 582), (6, 774), (25, 578), (37, 2351), (19, 1390), (4, 309), (5, 560), (2, 136), (0, 54), (37, 246), (7, 812), (14, 1147), (2, 126), (27, 241), (37, 2057), (5, 26), (5, 333), (11, 1013), (31, 1917), (15, 1206), (2, 73), (20, 1098), (26, 478), (4, 312), (2, 54), (37, 139), (28, 359), (39, 295), (8, 922), (38, 296), (8, 209), (37, 1479), (37, 2302), (37, 2029), (12, 1018), 

In [41]:
print(len(removed_cells))

9855


In [42]:
import sklearn.metrics as metrics
M_cosine_similarity = metrics.pairwise.cosine_similarity(M)
#M_cosine_similarity = csr_matrix(M_cosine_similarity)
print(M_cosine_similarity.shape)

(4794, 4794)


In [43]:
import numpy as np
#M_cosine_similarity.flatten()
# flattened_M = M_cosine_similarity.flatten()
# flattened_M.sort()
# print(flattened_M)
#np.reshape(M_cosine_similarity,(1,4794*4092))

In [44]:
#set_diag 0 ώστε να μη μου στείλει στα max τα indices της διαγωνίου.
#εφαρμόζω argmax στον πίνακα που έθεσα την διαγώνιο σε 0
#πρέπει να βρώ σε ποιό axis θα το εφαρμόσω λογικά το axis = None
#max_args = A.argmax(axis=None)
#max_values = A.max(axis=None)

In [53]:
import sys
from scipy.sparse import csc_matrix
M_csc = csr_matrix.tocsc(M)
np.fill_diagonal(M_cosine_similarity,0)
predictions = []

for removed_cell in removed_cells:
    topk = []
    k=5
    i = removed_cell[0]
    j = removed_cell[1]
    # print(i,j)
    non_zero_ratings = csc_matrix.nonzero(M_csc[:,j])
    copy = np.copy(M_cosine_similarity[i,:])
    non_zero_users = non_zero_ratings[0]
    while k > 0:
        index = np.argmax(copy)
        if index in non_zero_users:
            #print(index,copy[index])
            topk.append((index,copy[index]))
            copy[index] = 0
            k -= 1
        else:
            copy[index] = 0
    sum_of_sim = 0
    sum_of_rating = 0
    for element in topk:
        sum_of_sim += element[1]
        sum_of_rating += M[element[0],j] * element[1]
    prediction = sum_of_rating/sum_of_sim
    predictions.append((i,j,prediction))
    M[i,j] = prediction
    # print(prediction)

18 1286
864 0.1864207120431663
2104 0.17765886991666768
2786 0.17464443146786116
264 0.16960151575998877
4551 0.15594745456022846
2.6209791885906855


SystemExit: 1

In [ ]:
print(predictions)